name: "pytorch-alignment"
on:
  pull_request:
    paths:
      - "cmake/**"
      - "config/**"
      - "python/**"
      - "setup.py"
      - "include/**"
      - "src/**"
      - ".github/workflows/pytorch-alignment.yml"
      - "tests/pytorch_alignment.sh"
  push:
    branches:
      - "master"
    paths:
      - "cmake/**"
      - "config/**"
      - "python/**"
      - "setup.py"
      - "include/**"
      - "src/**"
      - ".github/workflows/pytorch-alignment.yml"
      - "tests/pytorch_alignment.sh"
  workflow_dispatch:
concurrency:
  group: pytorch-alignment-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytorch-alignment-test-operators:
    name: Pytorch Alignment Test Operators
    runs-on: ubuntu-20.04
    env:
      FLEXFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Run Tests
        run: |
          cd $FF_HOME
          pip3 install pytest
          ../tests/pytorch_alignment.sh
